language: en-US
name: Brian M. Bailey
title: Brian M. Bailey's resume
description: The reasons people pay me to do things
timezone: Central/ Texas

#-- Local configuration
detach:  false
port:    4000
host:    127.0.0.1
